import Head from "next/head";
import { Header } from "../components/Header";
import { Hero } from "../components/Hero";

export default function Home() {
	return (
		<div className="bg-[#242424] h-screen text-white">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Header */}
			<Header />
			{/* Hero */}
			<Hero />
			{/* About */}

			{/* Skills */}

			{/* Achivements */}

			{/* Contact Me */}
		</div>
	);
}
